apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: prometheus-example-app
  name: prometheus-example-app
spec:
  selector:
    matchLabels:
      app: prometheus-example-app
  podMetricsEndpoints:
  - port: http-server