apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-example-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-example-app
  podMetricsEndpoints:
  - port: http-server